### ISSUE TITLE
Is there a simple command line interface for the OCR part?

### ISSUE THREAD

**Issue by phortx** [seeebek/EliteOCR#15]
Awesome work!

I wonder if it's possible to use EliteOCR via a bash. Is there a simple CLI call? Something like ...

`$ ocr.py Screenshot_0002.bmp`

which just does the OCR and outputs the pricings in some kind of data structure like JSON, XML or something like that?

Would be really nice.

**Comment by seeebek** [comment]
There is now a simple CLI. Output is a xml file with some additional information.
From source: EliteOCR.py -h

Compiled: go to bin directory and run EliteOCRcmd.exe -h

Usage: EliteOCRcmd -i input [-o output] [-s system] [-l lang]
    
    -i --input:   path to an image file
    -o --output:  defines where results should be written, default output.xml
    -s --system:  overrides the system name from log files
    -l --lang:    OCR language, must be one from this list: eng, deu, fra
    -h --help:    shows this help page
    -v --version: version info
    
Example: EliteOCRcmd.exe -i Screenshot_0014.bmp -o result.xml -s "Test System" -l fra
