### ISSUE TITLE
Please add time-zone info to time-stamps

### ISSUE THREAD

**Issue by MagmaiKH** [seeebek/EliteOCR#16]
Complete date plus hours, minutes and seconds:
YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)

Complete date plus hours, minutes, seconds and a decimal fraction of a
second
YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

Without the time-zone info, when I receive an update over EDDN I don't know what the time really is.
(I have dates in the future in QAA now!)

**Comment by seeebek** [comment]
The time is in UTC! No time zone shift. You have to calculate how many hours you are shifted from UTC. The dates should not appear in the future compared to UTC. I check EDDN output and it look completely OK to me.

**Comment by MagmaiKH** [comment]
It should have +00:00 tagged on the end of it if it's in UTC.
Without that specification the interpretation is that the time is in _local time_.
