### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by beldougie** [seeebek/EliteOCR#21]
In preparation for the Mac OS release due in a couple of months. Should be possible thanks to Python. Would be happy to fork and lend a hand if you like?

**Comment by seeebek** [comment]
I don't own a Mac so I cannot test it. You are welcome to fork it and test the functionality on a mac. How ever be prepared for some issues.

**Comment by beldougie** [comment]
No worries. I'll have a little play when I can get some time. No doubt there will be issues with porting, but we'll see how bad they are lol.

Cheers seeebek

**Comment by demonbane** [comment]
@beldougie Did you have a chance to start testing this? I'm wanting to do the OCR on my laptop while running Elite on my desktop so that I don't have to switch in and out. I'm happy to help any way I can.

**Comment by beldougie** [comment]
I haven't yet. I did fork the project and had a quick look, but that was as far as I got. I'm more interested in having it available once the Mac of ED comes out TBH so it hasn't been high on my radar just yet. Feel free to jump in :)

**Comment by beldougie** [comment]
@demonbane Quick update, I hadn't forked the project apparently, but I did last night and after a little while of faffing about installing requirements, I have a version running from the source but all I've had time to test so far is the application starts on the Mac, I did not have any images to OCR to hand. I'm hoping to get a chance to test that this afternoon, but will definitely over the weekend at some point.

If you want to have a look at the current source, go along to my fork here: https://github.com/beldougie/EliteOCR most of the changes were updating the README with missing requirements and adding a requirements.txt file (for simple installation using pip) and a change to the environment variable key so that it is compatible with both windows and posix.

Once I have a working version, I will create a PR for @seeebek and I'll be happy to volunteer test and build services for any future updates.

One last note, I plan to raise mac specific issues on my fork for now rather than clutter the system here. So if you do try it out and find issues, it might make sense to follow suit. Although I shall monitor this repo as well of course!

**Comment by demonbane** [comment]
@beldougie I ended up creating my own fork just because doing PRs on a fork of a fork is a pain. The additional info you put in the README definitely helped me get it running on my system though. Now if only I could get a good copy to be produced by `pyinstaller` we'd be all set. (I think the big issue there is the tessdata problem you mentioned in #25.)

**Comment by seeebek** [comment]
You are not forced to use pyinstaller. If you find other tool which works it  would be great. Once you did the changes let me test it if it isn't breaking the windows version. Then I will happily merge it with master.

**Comment by demonbane** [comment]
Here's an experimental build of EliteOCR for Mac:

https://dl.dropboxusercontent.com/u/142407/EliteOCR.tar.gz

I've only been able to test it on two computers so far, and it works fine on one and crashes on the other. If anyone decides to give it a shot I'd love to hear any feedback.

**Comment by demonbane** [comment]
There are some updated changes in #29 that include the recent 0.5.4.1 release. I'll post an updated Mac build once I've had a chance to finish testing.

**Comment by seeebek** [comment]
I did some merging and released the newest version. I resolve few problems especially with file system encoding. It would be nice if somebody could check what needs to be changed for mac compatibility.

**Comment by demonbane** [comment]
I just left a comment on the closed PR you had for merging dev. Just based off a quick grep for `<<<<<` in the tree, it looks like there's 31 merge conflicts that got committed here. I can try to resolve them, but since they're probably mostly your edits, it's probably best if you review them really quick. If you want me to try it and send a PR I can do that as well.

**Comment by seeebek** [comment]
I'm really bad with git :-/ I will clean those by hand and recommit...

**Comment by seeebek** [comment]
Ok. I cleaned it. After installing all dependencies it worked out of the box on ubuntu.

**Comment by robinas** [comment]
Hi, It sounds like EliteOCR on a MAC is running. I would like to assist in testing if I can. Programming is not my current strong point but interested to learn. 
-  Is Python 2.7 a requirement, can I use 3.4? Since current python version on OS X 10.10 is 2.6.9.
- currently have TD on the MAC I want to use to test.

**Comment by seeebek** [comment]
I'm not really sure about the python version. I developed it with 2.7.x. You can try with 2.6.9. I'm sure 3.x will not work.
It would be nice if you could tell me about standard paths for the game on mac(where screenshots are being saved, where are the log files and where is AppConfig.xml)

**Comment by robinas** [comment]
I can certainly help with log files and AppConfig is located. I can run multiple Python versions, do for TD and see what pans out.

**Comment by robinas** [comment]
/Users/YourUserName/Library/Application Support/Frontier_Developments/Products/FORC-FDEV-D-1010/EliteDangerous.app/Contents/Resources/AppConfig.xml

/Users/YourUserName/Library/Application Support/Frontier\ Developments/Elite\ Dangerous/Logs/
debugOutput  and netLog

R

**Comment by seeebek** [comment]
Great thanks. Is there a typo in the second one or is there really "\ "?
Do you think you would be able to create a easy install procedure/instructions for mac? What I mean is something like the instruction I did for Ubuntu. Maybe create a mac_setup.sh file for people who want to install all dependencies with one click to run it. Later a pyinstaller standalone would be nice when I start to make releases here.

**Comment by robinas** [comment]
The \ designates a space it is how it was displayed in the path so I left it.

**Comment by Marginal** [comment]
Re:  Appconfig
The path ~/Library/Application Support/Frontier_Developments/Products/FORC-FDEV-D-1xxx/EliteDangerous.app/Contents/Resources/AppConfig.xml is within the EliteDangerous application bundle, so altering this file will be problematic if Frontier sign the app in the future (e.g. to fix Firewall issues - https://forums.frontier.co.uk/showthread.php?t=144635).
The recommended way of overriding network settings on Mac seems to be to create a file AppConfigLocal.xml in ~/Library/Application Support/Frontier Developments/Elite Dangerous/ . See https://forums.frontier.co.uk/showthread.php?t=132740&page=3&p=2034952
My pull request #33 takes this approach.

Re: Installer
I'm currently working on this and hope to have a solution for creating a standalone app in the next day or two.

**Comment by seeebek** [comment]
Thanks. I had a look at the pull request but had no time to test and merge it. I will try to do it on sunday or  monday.

**Comment by robinas** [comment]
Sorry if this is a repeat.  I have managed to get EliteOCR running with python EliteOCr.py on two different computers. Am writing the steps using two different computers with slightly different Python routes, a MacBookPro and a Hackintosh both running 10.10.3. tools are a combination of brew and pip with one compile make, make install exception. Will also look at pyinstaller to try for the standalone app as I needed Xcode command line tools for both instances. More to follow tomorrow or afternoon. Oh yes screenshots, Mac users will have to either select F keys in keyboards preferences or use FN + F10 Hackintosh should be fine with just F10 unless they have a media savey keyboard. Location is Users/yourname/Pictures/Frontier Developments/Elite Dangerous/

**Comment by Marginal** [comment]
I have building a standalone app working in my commit 383de91ba2.
The file README.md is getting unwieldy so I split out the building instructions into a separate BUILDING.md file, if that's OK?

**Comment by robinas** [comment]
Hi,
I have documented a process to get a isolated version of python 2.7.9  installed with all the modules without having to do any python configure.py, make and make install. This leaves a functional python environment where you can then run python EliteOCR.py in the directory and have the program run. It is also ready to try building the standalone App with pyinstaller (under options works). 
I am bad with GIT so will put the instructions in this email for peer review and comment. 


MAC Requirements - tested on OS X 10.10.3
To manually install EliteOCR on OS X it is recommended to use Homebrew which is a package manager
and will help keep different versions of python
from interferring with the System version that is part of OS X.

HomeBrew
http://brew.sh 
- for better explanation and documentation

http://matthewcarriere.com/2013/08/05/how-to-install-and-use-homebrew 
- another helpful site steps through the xcode-select information, he suggests running xcode first.
- I have done both ways but you will need xcode command line so quicker to apply at this point.

xcode-select --install

http://brew.sh

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Python 2.7
This will install python 2.7.9 in a compartmentalized manner

brew install python

Numpy

brew install numpy

- should be part of python but try anyways to confirm


OpenCV for MAC requires 

brew tap homebrew/science 

- needs to be installed before brew can install opencv

brew install opencv 

- this installs NUMPY if it isn't yet installed

pip install 

SIP
Install before PyQt4

brew install sip

PyQt4

brew install pyqt

qimage2ndarray

pip install qimage2ndarray

Openpyxl

pip install openpyxl

Ezodf

pip install ezodf

Lxml

http://geekforbrains.com/post/how-to-install-lxml-for-python-using-homebrew-and-pip-in-3-steps
- this needs xcode command line tools installed, if you haven't do so now
xcode-select --install   - follow directions, you will have to accept the license 
when you run the following two lines

brew install libxml2

pip install lxml

Python-Levenshtein

pip install python-Levenshtein

PyTZ

pip install pytz

tzlocal

pip install tzlocal

Requests

pip install requests

Grequests

pip install grequests

bitarray

pip install bitarray

Should run brew doctor at this point - fix any problems, some warnings are ok

brew doctor

Make sure you remember to download the EliteOCR source, expand - change to the EliteOCR directory 

python EliteOCR.py

If all goes well you should get a flashing Python icon, select to go to the EliteOCR setup screen.

**Comment by Marginal** [comment]
I've uploaded a test build build here: https://github.com/Marginal/EliteOCR/releases/tag/0.6.0.9
This should work on OSX 10.9 & 10.10.
I'm struggling with getting the Sparkle Framework integrated for updating so this build still uses the Windows update mechanism. Otherwise it should be fully functional.
Please report any issues.

**Comment by robinas** [comment]
Hi Marginal,

Checked out looks good overall, missing the Trade Dangerous Export button??

**Comment by Marginal** [comment]
@robinas Glad it works on your macine - packaging Python apps on OSX is a nightmare.
Trade Dangerous export should be fixed in: https://github.com/Marginal/EliteOCR/releases/tag/0.6.0.9-b2

**Comment by Marginal** [comment]
Another test build: https://github.com/Marginal/EliteOCR/releases/tag/0.6.0.9-b3

**Comment by robinas** [comment]
I have run the the latest build 0.6.0.9-b3. testing on OS X 10.10.3. No surprises, the TradeDangerous export button is there and the export file is now correctly named and located as per Path setup. Ran color Calibration and Learning wizard successfully as far as I can tell. Exported BPC, EDDN and Trade Dangerous with no apparent errors. I didn't sniff the output and both TD import and MadDavo accepted the import. One question as this is presented as a App, where does the errorlog.txt go when it is generated?  Otherwise looking good. Will test on a couple of other MACs but all are 10.10.3 no 10.9.x

**Comment by Marginal** [comment]
Great. I haven't sniffed the output either but I can see in ross.eddb.io that EDDN is accepting the data.

Good point about errorlog.txt. It gets written to EliteOCR.app/Contents/Resources/errorlog.txt which isn't very accessible, and which invalidates the app's signature.

In 804ea67 I've changed this to write ~/Library/Logs/EliteOCR.log, from where it can be viewed in the Console app.

**Comment by seeebek** [comment]
Wow guy. I see you did a lot of progress. I'm sorry I couldn't find the time yet to merge the changes. I'm affraid you will have to wait until the weekend.
Once I confirm they don't break the windows version I will make a release. I will also ask one of you to provide me the standalone file so I can officially provide it on sourceforge. I hope I can trust you with not including any malicous functions.

**Comment by Marginal** [comment]
@seeebek 
I'll provide a standalone file. It will be signed so any malicious activity could be traced back to me. (Apps on Mac pretty-much have to be signed).
I will also need to provide you with an "appcast" file that points to the standalone file and any future updates. (See http://gawker.sourceforge.net/appcast.xml for an example of such a file).

I've assumed in 17ba88d that you will place the standalone file at:
http://sourceforge.net/projects/eliteocr/files/0.6/EliteOCR_mac_0.6.x.y.zip
and the appcast file at:
http://eliteocr.sourceforge.net/appcast.xml

Please let me know if you'd like me to change those names/places.

**Comment by seeebek** [comment]
Very good to hear this. Your suggested names and locations on sourceforge seem very good.
What still needs to be done is to change the update check and update download part of EliteOCR in order to make it work with your changes. Do you think you can have a look to this?

I plan to work on this on weekend. I would include the PR and few small changes I still need to do. I will call the version 0.7 since mac compatibility is quite a big milestone.

**Comment by robinas** [comment]
@Marginal 
I have one item to note, seems informational. When I start the App in a first instance after download/install it will quit. Subsequent starts are fine. Looked on console and it states the following; 
2015-05-21 3:32:20.803 PM EliteOCR[65425]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.10.3. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:

Just incase it needs to be mentioned in any Readme or notes.

**Comment by Marginal** [comment]
@seeebek 
Pull request #34 already contains the code required to auto-update the Mac build. The code is in [macupdate.py](https://github.com/Marginal/EliteOCR/blob/mac-build/macupdate.py) and the configuration in [setup.py](https://github.com/Marginal/EliteOCR/blob/mac-build/setup.py#L91) in that branch. I'm using the [Sparkle](http://sparkle-project.org/) framework to do the heavy lifting - it's the de-facto standard way to do auto-updates on Mac for apps not in Apple's App store.

@robinas 
Thanks. It's related to the "EliteOCR is an application downloaded from the internet" message. (The Gestalt warning is a red-herring and is generated by the Qt runtime). I'm working on a fix.

**Comment by seeebek** [comment]
Ah ok, I didn't understand it first time. You don't need to change anything about the windows one. I just need to make sure it's not confusing the mac files with a new update.

**Comment by Marginal** [comment]
@seeebek 
Good point - I hadn't looked carefully at your update code. Fixed in a845981.

**Comment by seeebek** [comment]
@Marginal 
after initial tests everything seems to work so I merged it to master. I will test it a little bit more and think what else needs to be done for 0.7.

**Comment by Marginal** [comment]
Excellent. Thanks.

**Comment by robinas** [comment]
@Marginal 
Hi,  Since the source has been updated, I now get the following when I try to run with Python.
Python EliteOCR.py now gives me
/settings.py", line 17, in <module>
    from Foundation import NSHomeDirectory, NSSearchPathForDirectoriesInDomains, NSDocumentDirectory, NSApplicationSupportDirectory, NSPicturesDirectory, NSUserDomainMask
ImportError: No module named Foundation

**Comment by Marginal** [comment]
@robinas
It needs PyObjC.
Either launch with `/usr/bin/python ./EliteOCR.py` which should invoke the pre-installed system Python, or install PyObjC into your homebrew Python. Maybe `pip -U pyobjc pyobjc-core`.

**Comment by robinas** [comment]
Perfect, thanks for the knowledge :-)

**Comment by robinas** [comment]
@Marginal 
next error when running python ./EliteOCR.py, macupdate.py give this;
macupdate.py", line 13, in init
    self = super(Delegate, self).init()
AttributeError: 'super' object has no attribute 'ini

I am using python 2.7.9 and OS X 10.10.3 with Xcode 6.3.2
My reading implies that the super is depreciated, any thoughts?

**Comment by Marginal** [comment]
@robinas 
Does replacing line 13 wit the following solve the problem?
```python
self = objc.super(Delegate, self).init()
```

**Comment by robinas** [comment]
@Marginal 
It does indeed resolve the problem. Thank you for your help.

**Comment by Marginal** [comment]
@robinas 
Great. Fixed in 43726b6 in pull request #37.

**Comment by seeebek** [comment]
I'm closing this issue as the mac version gets officially released. New issues can be created separately for better understanding.
