### ISSUE TITLE
Fail 'Export to EDDN' when 2 screenshots have overlapping market items

### ISSUE THREAD

**Issue by lbatalha** [seeebek/EliteOCR#22]
Happens mostly when market is scrolled all the way to the bottom, and some of the first goods are also present in the previous screenshot.

errorlog.txt: 
```
2015-02-08 16:34:50,950 CRITICAL:
n  File "C:\Users\SEBAST~1\Desktop\RFACTO~2\build\EliteOCR\out00-PYZ.pyz\export", line 194, in eddnExport

<type 'exceptions.TypeError'>: arguments did not match any overloaded call:
  QMessageBox.warning(QWidget, QString, QString, QMessageBox.StandardButtons buttons=QMessageBox.Ok, QMessageBox.StandardButton defaultButton=QMessageBox.NoButton): argument 1 has unexpected type 'instance'
  QMessageBox.warning(QWidget, QString, QString, int, int, int button2=0): argument 1 has unexpected type 'instance'
  QMessageBox.warning(QWidget, QString, QString, QString, QString button1Text=QString(), QString button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1): argument 1 has unexpected type 'instance'
```
Example of overlap
SS1: https://a.pomf.se/sfnpxw.png
SS2: https://a.pomf.se/hauuxx.png

Exporting normally and to BPC does not seem to produce any errors.

To overcome this I have been taking a screenshot and exporting everything except the final part of the market, and then exporting just that final part individually.

**Comment by seeebek** [comment]
I found the problem. It will be fixed today.
