### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by risa2000** [seeebek/EliteOCR#27]
I wanted to do it hard way and run it from the source, so I went through the list of dependencies and on top of what is already mentioned in readme I had to install:

    pip install pytz
    pip install tzlocal
    pip install beautifulsoup4
    pip install scikit-learn (did not work through pip, installed from pre-built package)
    pip install scipy (did not work through pip either)
    pip install requests
    pip install wget

I am on Windows 7 64-bit, running Python 2.7.9 32-bit, I have VC environment installed, so technically I should be able to build any C module too. I believe I installed superpack of scipy, which probably pulls in more stuff than necessary (possibly numpy as well), but it seemed to be already too much of mess trying to install scipy "pure".

I departed from official Python install from python.org. I guess maybe some of the packages listed above are already present in some other Python distros, but for what concerns the vanilla install, they are not.

**Comment by beldougie** [comment]
Have a look on my fork @risa2000, I have already updated this and got it working on Mac OSx. I've also updated the README with all the relevant information. Might help you out.

**Comment by risa2000** [comment]
Actually, I believe I made it working at the end - sort of. I just thought I should report the discrepancy between readme and my experience. The only problem I have, when I quit the app, it does not quit but "stops responding" and I need to kill the process manually.

**Comment by seeebek** [comment]
I'm rewriting the OCR part. This will result in dropping beautifulsoup4, scikit-learn, scipy and python tesseract. Those dependencies will not be necessary anymore. I will update README files in near future.

**Comment by seeebek** [comment]
I think now all dependencies are listed. I will close this thread. If there are any missing please reopen.
