### ISSUE TITLE
TypeError QVariant - Ubuntu

### ISSUE THREAD

**Issue by dphilpot** [seeebek/EliteOCR#35]
Hi,

i wanted to try EliteOCR under Ubuntu. Like mentioned in the description i installed all dependency (btw. BeautifulSoup4 is missing in the ReadMe) and i get this error in the errorlog.txt directly after executing the script.

```
2015-05-23 16:53:53,174 CRITICAL:
  File "EliteOCR.py", line 1215, in <module>
    sys.exit(main(sys.argv[1:]))
  File "EliteOCR.py", line 1208, in main
    window = EliteOCR(app)
  File "EliteOCR.py", line 84, in __init__
    self.settings = Settings(self)
  File "/home/dennis/Dokumente/Elite/EliteOCR/settings.py", line 24, in __init__
    self.values = self.loadSettings()
  File "/home/dennis/Dokumente/Elite/EliteOCR/settings.py", line 57, in loadSettings
    'horizontal_exp': self.reg.value('horizontal_exp', type=bool),

<type 'exceptions.TypeError'>: unable to convert a QVariant of type 0 to a QMetaType of type 1
```

**Comment by seeebek** [comment]
@dphilpot 
I added beautifulsoup to the list.
I could not reproduce your error. I'm running it on Ubuntu 15.04 amd64. Relatively clean installation.
Could you describe your setup?

**Comment by dphilpot** [comment]
Hi @seeebek 
im Running a Clean Ubuntu trusty (14.04 i think) on a 32Bit System.
Maybe the 32Bit seems to be the Problem?

**Comment by seeebek** [comment]
@dphilpot 
the problem is that QVariant of type 0 is "invalid". QVariant of type 1 is "bool". QMetaType of type 1 is "bool". So it means when it reads the settings from /home/user/.config/seeebek/eliteOCR.conf it gets a wrong value. There should be a line like:

horizontal_exp=false

Could you check if this file is created, what are the permissions and if the content looks ok?

**Comment by dphilpot** [comment]
Hi @seeebek

horizontal_exp=false was indeed missing. Fixed that and now im getting this error.

```
2015-05-24 19:11:41,033 CRITICAL:
  File "EliteOCR.py", line 1215, in <module>
    sys.exit(main(sys.argv[1:]))
  File "EliteOCR.py", line 1208, in main
    window = EliteOCR(app)
  File "EliteOCR.py", line 84, in __init__
    self.settings = Settings(self)
  File "/home/dennis/Dokumente/Elite/EliteOCR/settings.py", line 24, in __init__
    self.values = self.loadSettings()
  File "/home/dennis/Dokumente/Elite/EliteOCR/settings.py", line 59, in loadSettings
    'last_export_format': self.reg.value('last_export_format', type=QString),

<type 'exceptions.TypeError'>: unable to convert a QVariant of type 0 to a QMetaType of type 10
```

**Comment by seeebek** [comment]
@dphilpot 
It looks like yours eliteOCR.conf was not generated properly but I cannot find out why. Did you try deleting it? Did you try redownloading the source and running again?

**Comment by dphilpot** [comment]
@seeebek 

Yes i tryed it just a moment ago.

Delete config => Same Problem as mentioned above

```QVariant of type 0 to a QMetaType of type 1```

Remove all relevant data (Config, Checkout directore etc..) clean checkout, some problem.
Added the value in the config i get the type 10 Problem again.

Removed all again and check every into a different folder /opt/test/EliteOCR and i get the same problem again.

You should get simular effects if you create a Ubuntu 14 32Bit VM in VirtualBox, because i got nothing different as a default installation ATM.

Cheers

Dennis

**Comment by dphilpot** [comment]
any news?

**Comment by seeebek** [comment]
@dphilpot 
Sorry for the waiting time. I finally had time to sit down and install ubuntu 32 bit. 
The problem is now solved. Just download the newest code from here.
